### ISSUE TITLE
Support for ServerPrerendered for Blazor Server App

### ISSUE THREAD

**Issue by nolisj** [David-Moreira/BlazorXTabs#40]
I consider this a feature request rather than a bug since I'm not sure if this is supposed to work under Blazor Server (not Blazor WebAssembly).

To replicate, create a new Blazor Server app and set the render-mode of the project to ServerPrerendered. Setting it to ServerPrerendered causes an exception.

Setting in _Host.cshtml:
`<component type="typeof(App)" render-mode="ServerPrerendered" />`

Exception when launching the home page:

"... System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state. ..."

Changing the render-mode setting to "Server" fixes it.

**Comment by David-Moreira** [comment]
Hello @nolisj 
Are you `XTabsRouteView` by any chance? Only way I was able to reproduce this on the BlazorXTabs demo app was by setting `ServerPrerendered` and having `OnTabAdded` set. 

I made sure to solve it on the demo by making sure the UI thread is called just like suggested by the exception.
![image](https://user-images.githubusercontent.com/22283161/191853306-5dbef54b-74f7-4fde-8982-124d1501bbd4.png)

Let me know if this helps solve your problem. Otherwise a repo reproducing the problem would be great!

Thanks!
